<#
.SYNOPSIS
  Drives the local Ansible validation loop against a sshd container.

.DESCRIPTION
  Subcommands:
    init    Generate ed25519 keypair + a deploy/dev-staging/secrets.test.env
            with sane defaults
    up      Build + start the linux_staging and ansible_runner containers
    keyscan Capture linux_staging's host fingerprint into known_hosts
    lint    Run ansible-playbook --syntax-check + ansible-lint
    check   Run ansible-playbook --check --diff (no side effects)
    apply   Run the real deploy
    health  Curl the deployed API on host port 8100
    down    docker compose down -v (full teardown)
    shell   Drop into a bash shell in ansible_runner

  All commands operate on the deploy/dev-staging/docker-compose.yml project.
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory=$true, Position=0)]
  [ValidateSet('init', 'up', 'keyscan', 'lint', 'check', 'apply', 'health', 'down', 'shell', 'logs', 'ps')]
  [string]$Command
)

$ErrorActionPreference = 'Stop'
$here = $PSScriptRoot
$repoRoot = (Resolve-Path (Join-Path $here '..\..')).Path
$keysDir = Join-Path $here 'keys'
$composeFile = Join-Path $here 'docker-compose.yml'
$varsFile = Join-Path $here 'extra_vars.yml'

function Invoke-Compose {
  param([Parameter(ValueFromRemainingArguments=$true)][object[]]$ComposeArgs)
  & docker compose -f $composeFile @ComposeArgs
  if ($LASTEXITCODE -ne 0) { throw "docker compose failed (exit $LASTEXITCODE)" }
}

# Cmd is captured as a single shell string passed to `sh -c`, so any -flags in
# the inner command don't get gobbled by PowerShell's parameter binder.
function Invoke-Runner {
  param([Parameter(Mandatory=$true)][string]$Cmd)
  & docker compose -f $composeFile exec -T ansible_runner sh -c $Cmd
  if ($LASTEXITCODE -ne 0) { throw "ansible_runner exec failed (exit $LASTEXITCODE)" }
}

switch ($Command) {

  'init' {
    if (-not (Test-Path $keysDir)) { New-Item -ItemType Directory -Path $keysDir | Out-Null }
    $privKey = Join-Path $keysDir 'dev_staging_id_ed25519'
    if (Test-Path $privKey) {
      Write-Host "Keypair already exists: $privKey" -ForegroundColor Yellow
    } else {
      Write-Host "Generating ed25519 keypair..." -ForegroundColor Cyan
      # Splat args via array so PowerShell passes the empty -N argument as a
      # true empty string. The earlier '""' form ended up as a literal "" passphrase.
      $kgArgs = @('-t', 'ed25519', '-f', $privKey, '-N', '', '-C', 'dev-staging@local', '-q')
      & ssh-keygen @kgArgs
      if ($LASTEXITCODE -ne 0) { throw "ssh-keygen failed (exit $LASTEXITCODE)" }
      # Re-write the pubkey with LF line endings — ssh-keygen on Windows
      # writes CRLF which sshd in the container treats as a malformed key.
      $pub = (Get-Content "$privKey.pub" -Raw).TrimEnd("`r","`n")
      [System.IO.File]::WriteAllText("$privKey.pub", $pub + "`n")
    }
    # Ensure permissions ansible-runner will accept (mode 0600).
    icacls $privKey /inheritance:r 2>$null | Out-Null
    icacls $privKey /grant "$($env:USERNAME):(R)" 2>$null | Out-Null

    if (-not (Test-Path $varsFile)) {
      Write-Host "Writing $varsFile (local-only test values)..." -ForegroundColor Cyan
      $secret = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 48 | ForEach-Object { [char]$_ })
      $pgPwd = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 24 | ForEach-Object { [char]$_ })
      # Single-quoted here-string: no expansion, no backtick escapes. We
      # interpolate the random secrets manually with -replace below.
      $template = @'
# Auto-generated by dev_staging.ps1 init. Local-only test values; safe to
# regenerate. The Ansible playbook reads these via "-e @extra_vars.yml".
---
# We test against the same GHCR image the GH workflow would deploy, pinned to
# :latest so the apply step works without rebuilding. Edit to point at your
# fork if you forked the repo.
app_image: ghcr.io/techno-yogi/task-management
app_image_tag: latest

app_env: staging-local
app_port: '8100'
compose_project_name: sweep-staging-test

postgres_user: app
postgres_password: '__PG_PWD__'
postgres_db: appdb
postgres_max_connections: '200'
postgres_shared_buffers: 128MB

secret_key: '__SECRET_KEY__'

database_url_async: postgresql+asyncpg://app:__PG_PWD__@postgres:5432/appdb
database_url_sync: postgresql+psycopg://app:__PG_PWD__@postgres:5432/appdb?sslmode=verify-full&sslrootcert=/etc/ssl/postgres/server.crt
async_pg_ssl_ca_file: /etc/ssl/postgres/server.crt
app_celery_broker_url: redis://redis:6379/0
app_celery_result_backend: redis://redis:6379/1

api_async_db_pool_size: '20'
api_async_db_max_overflow: '20'
api_sync_db_pool_size: '10'
api_sync_db_max_overflow: '20'

web_concurrency: '2'
celery_worker_concurrency: '4'

worker_exec_replicas: '2'
worker_aggregate_replicas: '1'
worker_sweep_finalize_replicas: '1'

# Skipped on a fresh image since the public GHCR repo does not require auth.
# Override via -e ghcr_username=... -e ghcr_token=... if you switch repos.
ghcr_username: anonymous
ghcr_token: anonymous
'@
      $contents = $template.Replace('__PG_PWD__', $pgPwd).Replace('__SECRET_KEY__', $secret)
      Set-Content -Path $varsFile -Value $contents -NoNewline
    } else {
      Write-Host "$varsFile already exists, leaving alone" -ForegroundColor Yellow
    }
    Write-Host "init complete. Next: pwsh $($MyInvocation.MyCommand.Name) up" -ForegroundColor Green
  }

  'up' {
    if (-not (Test-Path (Join-Path $keysDir 'dev_staging_id_ed25519'))) {
      throw "No keypair found. Run: pwsh $($MyInvocation.MyCommand.Name) init"
    }
    Invoke-Compose build
    Invoke-Compose up -d
    # Wait for sshd.
    Write-Host "Waiting for sshd on linux_staging..." -ForegroundColor Cyan
    $deadline = (Get-Date).AddSeconds(30)
    while ((Get-Date) -lt $deadline) {
      $r = & ssh -i (Join-Path $keysDir 'dev_staging_id_ed25519') -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=NUL -o ConnectTimeout=2 deploy@localhost 'echo ok' 2>$null
      if ($r -eq 'ok') { Write-Host "  sshd ready" -ForegroundColor Green; break }
      Start-Sleep 2
    }
    Invoke-Compose ps
  }

  'keyscan' {
    Write-Host "Capturing linux_staging host fingerprint into known_hosts..." -ForegroundColor Cyan
    $known = Join-Path $keysDir 'known_hosts'
    Invoke-Runner 'ssh-keyscan -H linux_staging' | Set-Content -Path $known -NoNewline
    Write-Host "Wrote $known" -ForegroundColor Green
    Get-Content $known | Select-Object -First 5
  }

  'lint' {
    Write-Host "ansible-playbook --syntax-check..." -ForegroundColor Cyan
    # cd into deploy/ so ansible.cfg (roles_path = roles) is auto-picked up.
    Invoke-Runner 'cd /work/deploy && ansible-playbook -i dev-staging/inventory.local.ini playbooks/deploy.yml --syntax-check -e @dev-staging/extra_vars.yml'
    Write-Host "ansible-lint..." -ForegroundColor Cyan
    # ansible-lint is allowed to advise but not block.
    Invoke-Runner 'cd /work/deploy && ansible-lint playbooks/deploy.yml || true'
  }

  'check' {
    Write-Host "ansible-playbook --check --diff..." -ForegroundColor Cyan
    Invoke-Runner 'cd /work/deploy && ansible-playbook -i dev-staging/inventory.local.ini playbooks/deploy.yml --check --diff -e @dev-staging/extra_vars.yml'
  }

  'apply' {
    Write-Host "ansible-playbook (real apply)..." -ForegroundColor Cyan
    Invoke-Runner 'cd /work/deploy && ansible-playbook -i dev-staging/inventory.local.ini playbooks/deploy.yml -e @dev-staging/extra_vars.yml'
  }

  'health' {
    Write-Host "GET http://localhost:8100/health" -ForegroundColor Cyan
    curl.exe -s -o - --max-time 5 http://localhost:8100/health
    Write-Host ""
    Write-Host "GET http://localhost:8100/health/ready" -ForegroundColor Cyan
    curl.exe -s -o - --max-time 5 http://localhost:8100/health/ready
    Write-Host ""
  }

  'down' {
    Invoke-Compose down -v --remove-orphans
  }

  'shell' {
    docker compose -f $composeFile exec ansible_runner bash
  }

  'logs' {
    Invoke-Compose logs --tail=50 -f
  }

  'ps' {
    Invoke-Compose ps
  }
}
